---
title: "Annotations"
output: html_document
date: "2023-06-20"
---

```{R}

#Load libraries

library(stats)
library(tibble)
library(reshape2)
library(ggplot2)
library(scales)
library(parallel)
library(cvequality)
library(readxl)
library(pbapply)
library(qvalue)
library(gplots)
library(gridExtra)
library(ggpubr)
```

```{R}

## load in data
RNA_Seq_expression_raw_data <- 
read.delim("brca_tcga/data_RNA_Seq_v2_expression_median.txt", stringsAsFactors = FALSE)

#The 'all' approach to check if all values in a row are 0
check_if_not_zero <- function (vector, number = 0) {
  if (!(all (vector == number))) {
    return (TRUE) #if not zero, then returns TRUE
  }
  else{
    return(FALSE)
  }
}

#See if there are any rows that are FALSE, meaning that are actually all 0
all(as.vector(unlist(apply(RNA_Seq_expression_raw_data[,-1:-2], 1, check_if_not_zero)))) 
zero_genes = as.vector(unlist(apply(RNA_Seq_expression_raw_data[,-1:-2], 1, check_if_not_zero)))

#take out genes with no expression in any of the patients
RNA_Seq_expression_raw_data = RNA_Seq_expression_raw_data[as.vector(unlist(apply(RNA_Seq_expression_raw_data[,-1:-2], 1, check_if_not_zero))),]

```

```{R}

gene_medians = apply(RNA_Seq_expression_raw_data[, -c(1,2)], 1, median)

```

```{R}

#' Copy and paste Brian's analysis from this point on
## ---- Data loading-------------------------------------------------------------

#Load in chromatin organization modifiers. How this was found: GO term, eukaryota => #mammalia => homo sapiens. Gives a list of gene products; there's non-unique entries #(contributed by different sources, etc)

chromatin_modifiers <- read.delim("brca_tcga/Chromatin_modifiers.txt", header=FALSE, stringsAsFactors=FALSE)

#the first column is the one of interest
colnames(chromatin_modifiers)[1] <- 'Gene Names'

chrom_list_to_sort_against <- unique(chromatin_modifiers$`Gene Names`)

#check lengths of new and original list from chromatin modifiers

length(chrom_list_to_sort_against) 
length(chromatin_modifiers$`Gene Names`)

#logic to extract the chromatin modifier genes specifically from the full RNA Seq list.
#Use the %in% operator to (vector-wise) get the rows specifically. Use this to get
#the quartiles for each gene:

set.seed(42)

chromatin_genes_RNA_seq <- RNA_Seq_expression_raw_data[RNA_Seq_expression_raw_data$Hugo_Symbol %in% chrom_list_to_sort_against,]

#And these are the 'true' groupings. Let's add a column to denote that here, in front
#of the first two columns using the 'add_column' function from tibble library:

chromatin_genes_RNA_seq <- add_column(chromatin_genes_RNA_seq,
                                      Random = 'N', .after = 2)

length(rownames(chromatin_genes_RNA_seq))

#We'd like to also derive a background distribution for all of these genes. To do so,
#let's append 50 genes that are randomly selected from the dataset, and their #corresponding rows. 

random_genes <- sample(RNA_Seq_expression_raw_data$Hugo_Symbol, 50)
random_genes_RNA_seq <- RNA_Seq_expression_raw_data[RNA_Seq_expression_raw_data$Hugo_Symbol %in% random_genes,]

random_names <- random_genes_RNA_seq$Hugo_Symbol

#Let's also add an equivalently named column here to denote that these are the random genes: 

random_genes_RNA_seq <- add_column(random_genes_RNA_seq, Random = 'Y', .after = 2)

full_genes_RNA_seq <- rbind(chromatin_genes_RNA_seq, random_genes_RNA_seq)

length(rownames(full_genes_RNA_seq)) == 
length(rownames(chromatin_genes_RNA_seq)) + length(rownames(random_genes_RNA_seq)) #TRUE

#creating a threshold with which to create 'hi' vs 'lo' populations of patients; here, I #choose to use top vs bottom quartile. Need to apply quantile across the rows of the #chromatin_genes data frame, excluding the first observation (which is a character string #of the gene name in question)

q25 <- apply(full_genes_RNA_seq[,-1:-3], 1, quantile, probs = c(0.25), na.rm = TRUE)

q75 <- apply(full_genes_RNA_seq[,-1:-3], 1, quantile, probs = c(0.75), na.rm = TRUE)


full_genes_RNA_seq <- add_column(full_genes_RNA_seq, q25 = q25, q75 = q75, .after = 3)

all (full_genes_RNA_seq$q25 <= full_genes_RNA_seq$q75) #true

#Also remove data where the bottom quartile is 0 FPKM. This doesn't seem like it would
#provide any meaningful data to a CV comparison.

full_genes_RNA_seq <- 
full_genes_RNA_seq[!(full_genes_RNA_seq$q25 == 0),]

#Viewing the data and indices
ggplot(full_genes_RNA_seq) + geom_density(aes (x = q25), color = 'red') +
geom_density (aes (x = q75), color = 'green') + 
labs (title = 'Plot of top and bottom quartiles of FPKM for chromatin organizers', 
      subtitle = 'Red = q25, Green = q75',
      x = 'Log10 Quartiles') + 
scale_x_log10()

```

```{R}
#' ### Getting groupings of the data based on chromatin modifier expression
#' 
#' We've now completed some EDA of the data and cleaning of useless chromatin modifier factors that wouldn't be good for grouping. Now, let's get dataframes corresponding to these groupings in a list format to each unique chromatin modifier, then use these groupings to get subsetted dataframes from the full dataset corresponding to bottom/top expressers of each chromatin modifier.
#' 
## ---- Getting lo/hi groupings--------------------------------------------------

#Now I want lo and hi expressers (below q25, above q75) for each gene. Way to approach #this: create different groupings, based on hi/lo threshold. To first get the groupings #and return #them in a list: define a function that returns up to three entries in list #format. These are: Gene name, all names below the bottom quantile, and all names above #the top quantile.

groupings_returner <- function (gene, chromatin_data, gene_col = 1, random = 3, 
                                q25_col = 4, q75_col = 5) {
  #the q25_col, q75_col are last two columns in the data frame
  q25 = chromatin_data[chromatin_data[,gene_col]==gene, q25_col] 
  q75 = chromatin_data[chromatin_data[,gene_col]==gene, q75_col]
  rand_designation = chromatin_data[chromatin_data[,gene_col]==gene, random] 
  #get the q25, q75 'indices'
  row = chromatin_data[chromatin_data[,gene_col]==gene, c(-1:-2, -random, 
                                                          -q25_col, -q75_col)]
  #eliminate gene ID, the q25 and q75 columns; isolate a single row
  col = data.frame(t(row)) 
  #get into column format for easy use of row subsetting techniques
  colnames(col) = 'expression_levels'
  list_below_25 = rownames(col[col$expression_levels <= q25,, drop= FALSE]) 
  #to keep row names
  list_above_75 = rownames(col[col$expression_levels >= q75,, drop= FALSE])
  return (list(gene, rand_designation, list_below_25, list_above_75)) 
  #list of 3 entries. First = gene, second = bottom quartile, third = top quartile
}

#let's test that this function works as intended: make a 'test' vector that corresponds 
#to the ACTB gene, then compare this to the corresponding list in the full list.
#Note that the 1103 and 1104 columns correspond to the q25, q75 columns correspondingly.

test <- groupings_returner('HDAC2', full_genes_RNA_seq)

str(test) #should look like a 4 item list of 

#Some warnings will occur: this is because I sampled 50 randomly from the full dataset.
#Some overlapped with the list of chromatin modifiers list. This seems reasonable to 
#keep though.

groupings <- lapply(full_genes_RNA_seq$Hugo_Symbol, groupings_returner,                                       full_genes_RNA_seq)
```

```{R}
# Name groupings
names(groupings) <- sapply(groupings, '[[', 1)

```

```{R}
#Groupings of Candidates
genesLeadCandidate = c('AURKA', 'AURKB', 'CDC45', 'CENPM', 'CENPN', 'H2AFZ', 'ASF1B', 'CDK1', 'ENY2', 'HJURP', 'HMGA1', 'JMJD6', 'MIS18A', 'NELFE', 'RNF8', 'RUVBL1', 'SUPV3L1', 'VRK1')

#Pull out x amount of random genes (designated by Y)

for (givenGene in groupings) {
  # Check if there is "Y"
  if (givenGene[[2]] == 'Y') {
    # If yes, append 1st index of sublist to the vec_of_strings
    genesLeadCandidate <- c(genesLeadCandidate, givenGene[[1]])
  }
}
rm(givenGene)

leadCandGroups = groupings[genesLeadCandidate]

```

```{R}
CNV_data = read.delim("brca_tcga/data_CNA.txt", header = TRUE, row.names = 1, stringsAsFactors = FALSE)
CNV_data  = CNV_data[,-1]
```

```{R}

groupings = groupings[genesLeadCandidate]

Groupings2 = groupings

unmatchedCounts_q25 = vector(mode = "numeric")
unmatchedCounts_q75 = vector(mode = "numeric")
unmatchedIDX_q25 = list()
unmatchedIDX_q75 = list()

for (i in 1:length(groupings)){
  unmatchedCounts_q25[i] = length(which(is.na(match(groupings[[i]][[3]], colnames(CNV_data)))))
  unmatchedCounts_q75[i] = length(which(is.na(match(groupings[[i]][[4]], colnames(CNV_data)))))
  unmatchedIDX_q25[[i]] = which(is.na(match(groupings[[i]][[3]], colnames(CNV_data))))
  unmatchedIDX_q75[[i]] = which(is.na(match(groupings[[i]][[4]], colnames(CNV_data))))
}

#Limit # patients
# Subtract out non-matching patients
q25_limit = 275-max(unmatchedCounts_q25)
q75_limit = 275-max(unmatchedCounts_q75)

limit = min(c(q25_limit, q75_limit))
q25_limit = limit
q75_limit = limit
rm(limit)

for (i in 1:length(groupings)){
  Groupings2[[i]][[3]] = setdiff(groupings[[i]][[3]], groupings[[i]][[3]][unmatchedIDX_q25[[i]]])
  Groupings2[[i]][[4]] = setdiff(groupings[[i]][[4]], groupings[[i]][[4]][unmatchedIDX_q75[[i]]])
  
}

## subtract out random till lower threshold met
set.seed(5)

for (i in 1:length(groupings))
  {
  if (length(Groupings2[[i]][[3]]) >= q25_limit){
    Groupings2[[i]][[3]] = sample(Groupings2[[i]][[3]], q25_limit)
  }
  
  if (length(Groupings2[[i]][[4]]) >= q75_limit)
    {
    Groupings2[[i]][[4]] = sample(Groupings2[[i]][[4]], q75_limit)
    }
}

```

```{r}
#Grouped CNV dataframes
stratified_q25_CNVs = list()
stratified_q75_CNVs = list()

for ( i in 1:length(Groupings2))
{
  stratified_q25_CNVs[[i]] = CNV_data[,Groupings2[[i]][[3]]]
  stratified_q75_CNVs[[i]] = CNV_data[,Groupings2[[i]][[4]]]
  
}
```

T-Test:

```{r}
## Calculate q75/q25 ratios 

#Avg CNV of patients for each gene
q75_means = lapply(stratified_q75_CNVs, function(x) apply(x, 1, mean))
q25_means = lapply(stratified_q25_CNVs, function(x) apply(x, 1, mean))

#Convert to numeric
q75_means = lapply(q75_means, as.numeric)
q25_means = lapply(q25_means, as.numeric)

#Calculate ratios of 75:25
q75_q25_ratios = mapply(function(x,y) x/y, q75_means, q25_means)

## convert NaNs and Infs to 1s (Tidy up data)
length(which(is.nan(q75_q25_ratios)))
q75_q25_ratios[which(is.nan(q75_q25_ratios))] = 1  # 1 = neutral
q75_q25_ratios[which(is.infinite(q75_q25_ratios))] = 1

stats = apply(q75_q25_ratios, 2, t.test, mu = 1)
stats.pvals = p.adjust(as.numeric(lapply(stats, function(x) x$p.value)))

## 
```

Chi-Square Test Revised


```{R}


```

```{r}
gene_names = rownames(stratified_q75_CNVs[[1]])
aa = vector(length = length(gene_names))
for (i in 1:length(gene_names)){
  aa[i] <- chisq.test(rbind( table(as.factor(stratified_q75_CNVs[[1]][i+10000,])), table(as.factor(stratified_q25_CNVs[[1]][i+10000,])) ),simulate.p.value = TRUE, B = 10000)$p.value
}

```


```{R}

#Take in all genes, compare CNV of q25 rows to q75 rows for given stratified gene
#Returns vector

geneApply <- function(stratifiedq75, stratifiedq25){
  gene_names = rownames(stratifiedq75)
  tempV = vector( length = length(gene_names) )
  for (i in 1:length(gene_names)){
    a = table(as.factor(stratifiedq75[i,]))
    b = table(as.factor(stratifiedq25[i,]))
    if (identical(names(a), names(b))){
      tempV[i] = chisq.test(rbind( a, b ),simulate.p.value = TRUE, B = 10000)$p.value
    } 
    else{
      df = matrix(0,2,5)
      colnames(df) = as.character(-2:2)
      df[1,match(names(a), colnames(df))] = as.numeric(a)
      df[2,match(names(b), colnames(df))] = as.numeric(b)
      tempV[i] = chisq.test(df,simulate.p.value = TRUE, B = 10000)$p.value
    }
  }

  return(tempV)
}


# Chi-squared test for a given gene

test2 = mapply(geneApply,stratified_q75_CNVs, stratified_q25_CNVs)

#gene_name = name of all the genes
#stratified_genes = the (57) stratified genes
  
  
  
  
  
  

# Get number of genes
num_genes <- length(stratified_q75_CNVs)

# lapply to perform chi-squared test for all genes
results_list <- lapply(1:num_genes, perform_chisq_test)

# Extract gene names and raw p-values
gene_names <- sapply(results_list, function(inner_list) as.character(inner_list[[1]]))
p_values <- sapply(results_list, function(inner_list) inner_list[[2]])
adjusted_p_values <- p.adjust(p_values, method = "bonferroni")

# data frame with results
results_df <- data.frame(GeneName = gene_names, PValue = adjusted_p_values)

print(results_df)

```

```{R}
#Nested for loop to get p-value of every gene:

for (i in 1:num_genes) {
    for (j in 1:num_genes) {
        # raw p-value
        raw_p_value <- perform_chisq_test(i, j)
        # change to adjusted p-value
        adjusted_p_values_matrix[i, j] <- p.adjust(raw_p_value, method = "bonferroni")
    }
}



```


Chi-Square Test:

```{r}
#' Now, because many of these hits correspond to chromosome segregation, etc. we would like to rule out copy number variation as a potential explanation for why these hits upregulate CV. Using a chi-square test, we should see similar distribution of -2, -1.. +2, between low and high expressers of each chromatin factor hit. If not, then this would suggest that the CV effect seen is 'artefactual'.
#' 
#' Run a chi-sq test for homogeneity for expression between the two groups (q10, q90). Basically, re-run the analysis but instead of using the asymptotic test, use the chi-sq test.



#Now, using this list of groupings, I should then create dataframes corresponding to each
#groupings list, i.e. for below bottom quantile and above top quantile. This function #should take in a 'key' (each LIST entry within the groupings list) and return either #nothing, or two dataframes.

dataframe_returner <- function (key, full_data, additional_col_vectors = c(),
                                key_gene_entry = 1, key_random_entry = 2, 
                                key_25_entry = 3, key_75_entry = 4) {
    #additional_col_vectors fetches columns by name
  
    #Idea is to aggr. the columns that correspond to the 'correct' patients for each
    #quartile grouping
    q25_dataframe = full_data[, colnames(full_data) %in% c(additional_col_vectors,
                                                           key[[key_25_entry]])]
    #key_2/75_entry is a numeric index
    q75_dataframe = full_data[, colnames(full_data) %in% c(additional_col_vectors,
                                                           key[[key_75_entry]])]
    return (list(key[[key_gene_entry]], key[[key_random_entry]],
                 q25_dataframe, q75_dataframe))
}

gene_vec <- c('Hugo_Symbol', 'Entrez_Gene_Id') 

#Need to now reapply the q25/q75 groupings to get two dataframes for this dataset
CNA_grouped_dataframes_list <- pblapply(groupings, dataframe_returner, 
                                      CNV_data, gene_vec)

#check that this list looks correct for a random gene, ACTL6A, index 1)
str(dataframe_returner(groupings[[1]], RNA_Seq_expression_raw_data, gene_vec)) 

#Code to actually get the grouped data
grouped_dataframes_list <- lapply(groupings, dataframe_returner, 
                                  RNA_Seq_expression_raw_data, gene_vec)

names_of_random <- unlist(lapply(CNA_grouped_dataframes_list, 
                          function (list) {if (list[[2]] == "Y") {
                            return (list [[1]])
                          }}
                  ))

#Test that the correct names were pulled out 
test_names <- unlist(lapply(CNA_grouped_dataframes_list[509:546],
                            function (list) {list[[1]]}))

length(names_of_random) == length(test_names)

#Define a function that will get fed into the test applier function defined previously

indices_to_omit = -1:-2 #the gene name, entrez ID

homogeneity_test <- function (row, q25_entry, q75_entry, list_of_df, 
                                omitted_indices) { 
  #getting the gene name, which is in the specified name entry column 
  #(generally first column)
  gene_name <- list_of_df[[q25_entry]][row, 1]
  #get rows of interest
  q25_fac <- factor((list_of_df[[q25_entry]][row, omitted_indices]))
  q75_fac <- factor((list_of_df[[q75_entry]][row, omitted_indices]))
  if (!all(levels(q25_fac) == levels(q75_fac))) 
    { #if the levels aren't shared b/w two groups, reassign levels or else get
    #incorrectly bound and uninterpretable table when calling rbind
    common_fac <- unique(c(levels(q25_fac), levels(q75_fac)))
    #call factor again with specified common set of factors; gives proper levels
    q25_table <- table(factor(q25_fac, levels = common_fac))
    q75_table <- table(factor(q75_fac, levels = common_fac))
  } else {
    #else just construct the table
    q25_table <- table(q25_fac)
    q75_table <- table(q75_fac)
  }
  #Need to rbind both the tables together into one contingency table; simulate p-vals 
  #10000 times to get more accurate Monte Carlo sims
  table_for_chi <- rbind(q25_table, q75_table)
  test <- chisq.test (table_for_chi, simulate.p.value = TRUE, B = 10000)
  return (list(gene_name, test$p.value))
}

```



```{R}
load("/Users/timothyliu/Documents/R/G/chiSqpValues.RData")

#tidyr, dplyr, ggplot


```


```{R}

transposed_CNV = t(CNV_data)
pca1 = prcomp(transposed_CNV, scale. = TRUE)
pca_coordinates = pca1$x

#Plot PCA1/PC2, only q25/q75 patients, each group diff color

#########################
#Plotting single PCA
#########################

pca1_df = data.frame(Sample = row.names(pca_coordinates), PC1 = pca_coordinates[,1], PC2 = pca_coordinates[,2])
pca1_df$Group <- NA

pca1_df$Group <- ifelse(pca1_df$Sample %in% names(stratified_q25_CNVs[[1]]), "q25", "q75")

test_plot1 <- ggplot(pca1_df, aes(x=PC1, y = PC2, color = Group)) +
  geom_point() +
  theme_minimal() +
  labs(color = "Sample Group") + ggplot2::ggtitle(paste(tNames[i])) + ggplot2::theme(plot.title = element_text(face="bold", size=18))

test_plot1

#prob have to use for loop
#ggarrange from ggpubr
  #takes list of plots and puts organizes them side by side
#list of plots
#57 diff PC plots

#List of ggplots
pca_ggplot_lists <- list()

#Name of genes
tNames <- names(groupings)

#Go through 57 genes (hits and random)
for (i in 1:length(groupings))
{
  pca_df_temp = pca1_df
  
  #Match to corresponding group
  pca_df_temp$Group <- ifelse(pca1_df$Sample %in% names(stratified_q25_CNVs[[i]]), "q25", "q75")
  
  #Create ggplot
  temp_plot <- ggplot2::ggplot(pca_df_temp, aes(x=PC1, y = PC2, color = Group)) + ggplot2::geom_point() + ggplot2::theme_minimal() + ggplot2::labs(color = "Sample Group") + ggplot2::ggtitle(paste(tNames[i])) + ggplot2::theme(plot.title = element_text(face="bold", size=18))

  
  #Add ggplot to list
  pca_ggplot_lists[[i]] <- temp_plot
}

rm(tNames)

combined_plots <- ggpubr::ggarrange(plotlist = pca_ggplot_lists, ncol = 10, nrow = 6)

#PDF
ggplot2::ggsave("combined_plots.pdf", plot = combined_plots, width = 140, height = 100, limitsize = FALSE)


```





```{R}
load("chiSqpValues_Original.RData")
dim(chiSq_pVals2)
head(chiSq_pVals2[[1]])
chiSq_pVals2[1:10,1:10]

?apply()

chiSq_pVals2[is.nan(chiSq_pVals2)] = 1
meanP = apply(chiSq_pVals2, 2, mean)

randomGeneMeans = mean(meanP[19:57])
stdGene = sd(meanP[19:57])
zScores = (meanP[1:18]-randomGeneMeans)/stdGene
hist(zScores)

```

PC Distances
```{R}
### This cell runs the PCA analysis on only the top 2000 DEGs (> 10 FPKM) ###
#### edited out non-DEG genes here ####

CNV_data = read.delim("brca_tcga/data_CNA.txt", header = TRUE, row.names = 1, stringsAsFactors = FALSE)
var.genes = readRDS('var_genes.RDS')
CNV_data = CNV_data[,-1]
CNV_data = CNV_data[intersect(var.genes, rownames(CNV_data)),]

### note for PCA here we are using the SVD algorithm
# The algorithm returns the same number of PCs as there are observations
## This is because SVD does not use the covariance matrix to compute PCs

pca = prcomp(t(CNV_data), scale. = TRUE)
PCA_coordinates = pca$x
PCA_coordinates_final = PCA_coordinates[, 1:50]
PCA_coordinates_final = as.data.frame(PCA_coordinates_final)

#List of dataframes
  #Dataframes hold PC coordinates of the top and bottom quartile patients for each of the gene stratifications from the total patient PC coordinates
dataframe_returner <- function (key, full_data, 
                                key_gene_entry = 1, key_random_entry = 2, 
                                key_25_entry = 3, key_75_entry = 4) {
  
  #key = groupings
  #full_data = pca
  #key_2/75_entry is a numeric index
  
  # Idea is to aggr. the columns that correspond to the 'correct' patients for each       # quartile grouping
  
  # Selecting rows based on patient names for q25 group
  q25_patient_names <- key[[key_25_entry]] #Names of patients
  q25_dataframe <- full_data[q25_patient_names, , drop = FALSE] #Match names with rownames from PCA and keep only those
  q25_dataframe <- na.omit(q25_dataframe)

  # Selecting rows based on patient names for q75 group
  q75_patient_names <- key[[key_75_entry]] #Names of patients
  q75_dataframe <- full_data[q75_patient_names, , drop = FALSE]
  q75_dataframe <- na.omit(q75_dataframe)
  
  return (list(
               key[[key_gene_entry]], 
               key[[key_random_entry]],
               q25_dataframe, 
               q75_dataframe))
}

#Apply to groupings
grouped_dataframes_list <- lapply(groupings, dataframe_returner, 
                                  PCA_coordinates_final)

grouped_dataframes_list_PCA_q25_q75_top2000DEGs <- grouped_dataframes_list
## groupings 494 - 543 are groupings based on random genes ##

#
transposer <- function(x){
  lower_pct = t(x[[3]][,-c(1,2)])
  upper_pct = t(x[[4]][,-c(1,2)])
  return(list(lower_pct, upper_pct))
}

library(pbapply)
grouped_dataframes_list_dist_prepped <- pblapply(grouped_dataframes_list, transposer)

library(parallelDist)

#find euclidean mean vector for cells per each drug treatment
centroid_appender <- function(x){
  lower_pct = rbind(colMeans(x[[1]]), x[[1]])
  upper_pct = rbind(colMeans(x[[2]]), x[[2]])
  return(list(lower_pct, upper_pct))
}

grouped_dataframes_list_dist_prepped2 <- pblapply(grouped_dataframes_list_dist_prepped, centroid_appender)

rm(grouped_dataframes_list_dist_prepped)

#parallelDist:
# Calculates the distances between the center of each quartile and all the points in that quartile
distance_calculator <- function(x){
  dist1 = parallelDist(x[[1]])
  dist2 = parallelDist(x[[2]])
  return(list(dist1, dist2))
}

#Stores distances in a list that has genes, which has q25 and 75 groups with their distances for each patient
distances_tmp <- pblapply(grouped_dataframes_list_dist_prepped2, distance_calculator)

#Stores distance
distance_extractor <- function(x){
  dist_lower_pct <- as.matrix(x[[1]])[-1,1]
  dist_upper_pct <- as.matrix(x[[2]])[-1,1]
  return(list(dist_lower_pct, dist_upper_pct))
}

distances_final <- pblapply(distances_tmp, distance_extractor)
distances_final -> distances_final_q25_q75_PCA_top2000DEGs
rm(distances_temp)

#Mean distance
mean_distance_calculator <- function(x){
  return(c(mean(as.numeric(x[[1]])), mean(as.numeric(x[[2]]))))
}

#Gets the mean distance of lower/higher percentile group for each gene
cluster_distances <- pblapply(distances_final, mean_distance_calculator)
cluster_distances <- do.call(rbind, cluster_distances)
cluster_distances <- as.data.frame(cluster_distances)
colnames(cluster_distances) <- c('lower_pctile', 'higher_pctile')
cluster_distances$high_to_low_ratio = cluster_distances$higher_pctile/cluster_distances$lower_pctile

#Creates new columns using the rownames from cluster_distances, and appends it to the dataframe
cluster_distances <- cbind(COs = rownames(cluster_distances), cluster_distances)

```
